# Dependencies
#markdown:         redcarpet
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Citeservlet 2
tagline:          "CITE services"
description:      'A full suite of CITE services in a single servlet, using data from a SPARQL endpoint'
baseurl: '/cs2/'


author:
  name:           'Neel Smith'
 

paginate:         5

links:
  - title: Github project
    url: https://github.com/cite-architecture/cs2
    external: true
   