# Dependencies
#markdown:         redcarpet
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Citeservlet 2
tagline:          "CITE services, second generation"
description:      'A full suite of CITE services in a single servlet, using data from a SPARQL endpoint'
baseurl: '/cs2/'


author:
  name:           'Neel Smith'
 

paginate:         5

links:
  - title: CTS subproject
    url: /cts
  - title: CITE services subproject
    url: /cite
  - title: CITE Image service subproject
    url: /citeimg
  - title: CITE Graph service subproject
    url: /graph
  - title: ORCA subproject
    url: /orca
  - title: Github repository
    url: https://github.com/cite-architecture/cs2
    external: true

